language: c

compiler:
    - gcc

cache: ccache

addons:
    apt:
        sources:
            - vala-team
        packages:
            - valac
            - libglib2.0-bin
            - libglib2.0-dev
            - libsoup2.4-dev
            - libfcgi-dev
            - python-pip
            - valadoc

install:
    - pip install --user cpp-coveralls sphinx PyYAML

before_script:
    - ./waf configure --enable-gcov
    - ./waf build

script:
    - ./build/tests/tests

after_success:
    - coveralls --repo-token $COVERALLS_TOKEN --build-root build
                --exclude build/examples --exclude build/tests
