dist: trusty

language: c

cache:
    - ccache
    - pip

compiler:
    - gcc

env:
    - VALAC=valac-0.30
    - VALAC=valac VALAFLAGS=--fatal-warnings

before_install:
    - sudo add-apt-repository --yes ppa:vala-team
    - sudo apt-get update --quiet
    - sudo apt-get install --yes --force-yes ${VALAC} libglib2.0-bin
      libglib2.0-dev libgnutls-dev libsoup2.4-dev libsystemd-journal-dev libfcgi-dev
      python3-pip gcovr libgee-0.8-dev libctpl-dev libjson-glib-dev
      libmemcached-dev libmarkdown2-dev liblua5.2-dev valgrind
    - pip3 install meson sphinx sphinx_rtd_theme PyYAML
    - wget https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-linux.zip
    - unzip ninja-linux.zip -d ${HOME}/.local/bin

before_script:
    - mkdir build
    - meson -D b_coverage=true -D enable_examples=true . build
    - ninja -C build -v
    - ninja -C build -v docs/en

script:
    - mesontest -C build --wrapper valgrind --print-errorlogs -v
    - DESTDIR=$(mktemp -d) ninja -C build -v install

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    irc: irc.gnome.org#valum
